### ISSUE TITLE
[WIP] Spec review

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#11]
https://github.com/jddf/spec/blob/master/draft-ucarion-jddf-xx.md:

- line 46: "JavaScript Object Notation (JSON) messages". Why "messages" and not "values" or "data" or "instances"?
- line 48: "standardized error indicators". Why not "messages" or just "errors" in this case?
- line 61: "The name JDDF is chosen to avoid confusion with "JSON
Schema" from {{I-D.handrews-json-schema}}." - seems unnecessary, even if this name stays. Depending on what is the confirmed scope of this spec (#6) we could name it accordingly so there is no confusion (#3).
- line 64: "There exist many options for describing JSON data". Seems unnecessary. There is no RFC for describing JSON data in JSON format (which is the most logical).
- line 65: "JDDF's expressiveness is strategically limited". Sounds apologetic. 
- line 83: "to a given mainstream programming language" -> to "many mainstream programming languages"?
- line 86: "Provide a standardized format for errors" - inconsistent with line 48 (see above)
- line 89: "JDDF is intentionally designed as a rather minimal schema language". Seems unnecessary. Minimal design is a reasonable expectation of any specification at RFC level.
- line 90: "JDDF can describe JSON, it is not able to describe its own structure". See "forms" form proposal in #7 that allows it with a simple addition to the spec.
- line 91: "Concise Data Definition Language (CDDL) {{RFC8610}} is used to describe" but in addition to that JDDF itself can be used as well along the spec, providing JDDF schema for each form and one final schema for the whole JDDF that implementation can use as an authoritative source defined as part of the spec (rather than JSON Schema meta-schema which is "informational").
- line 93: "JDDF makes code generation and standardized errors easier to implement" - I believe it would still be relatively simple with the most modern languages.
- line 95: "C++" - I would propose in addition to C++ (which I assume was chosen as the most basic) map to Haskell types (as one of the most advanced type systems). If I were to implement this spec, I would start from Haskell type for JDDF schema and implement quickcheck (exhaustive combinatorial testing for all possible values in the type space) that can be used against any language implementation (e.g. via HTTP) - it could be reference tester and implementation.
- line 103: "Signed and unsigned 8, 16, and 32-bit integers" - I think 64 bits could be included as SHOULD if not MUST - most (all?) languages support it one way or another, even JavaScript now with BigInt. I think it was included in JSL?
- line 317: "message". Is the intention to limit JDDF to JSON messages (e.g. rfc7493)? There are other use cases for JSON schemas, e.g. JSON stored in some database - PostgreSQL, Mongo, Elastic.
- line 401: "enum". As defined, it is problematic as it allows values that can map to multiple primitive or compound types. See proposal in #8
- line 402: "finite". It seems unnecessary to specify the list is "finite". Can you express infinite list in JSON?
- line 447: The sixth form, `properties`. Why not `struct`?
- line 452: "One of properties or optionalProperties may be omitted, but not both." I do not think it is correct to allow omitting "properties". The use cases when one or another properties is required can be covered by proposed "forms" in #7 . Currently, JDDF does not allow creating such restriction as quoted - if one puts all properties in optional, an empty object would also be valid. So the proposal it to stipulate that at least one property MUST be required (proposal in #9).
- line 513: "The seventh form, `values`". why not to call this form "map"? The member would still be "values", but the form name does not have to be the same (and there are other cases where they are not). Also see "type" proposal (#5)
- line 533: "the eighth form, `discriminator`". See proposal in #10 to merge it into `struct` form
- line 544: "To prevent ambiguous or unsatisfiable contstraints" - it is also addressed in #10.

to be continued...

**Comment by epoberezkin** [comment]
- line 658: "additionalProperties" - not sure about this idea tbh. JSON Schema became extremely confusing exactly because of that, as it is never clear "additional" to which list of properties. It would be easier of course to figure out for JDDL as static schema analysis is much easier, but still. Also "strict instance semantics" allows to validate with and without allowing additional properties using the same schema in both ways - the original approach seemed better. What's the use case, from data types point of view, to allow additional properties?
- line 732: "standard error indicator format" - same as above, why not "standard error format"?
- line 851: "Though non-root definitions are not syntactically disallowed in correct schemas" - I think they are disallowed, see line 254.
- line 1769: int64: RFC7493 says" "An example would be 64-bit integers, even though modern hardware can deal with them, because of the limited scope of JavaScript numbers." It is not longer the case and BigInt can be used in JavaScript code.

**Comment by ucarion** [comment]
Ok, will respond to each of these now. I would ask that if you have any retorts that are long-ish, that we create a new ticket and continue the discussion there. I'd like to see this issue closed, because I find tickets like this tend to languish.

---

> line 46: "JavaScript Object Notation (JSON) messages". Why "messages" and not "values" or "data" or "instances"?

Because that's the term the JSON RFC uses. It's the term of art.

> line 48: "standardized error indicators". Why not "messages" or just "errors" in this case?

Because "errors" is vague (it's a synonym for "mistake" or "flaw"), and "error messages" usually means something different -- just a string of some sort or something printed to stderr.

> line 61: "The name JDDF is chosen to avoid confusion with "JSON Schema" from {{I-D.handrews-json-schema}}." - seems unnecessary, even if this name stays. Depending on what is the confirmed scope of this spec (#6) we could name it accordingly so there is no confusion (#3).

Agreed that this language can be dropped if #3 happens.

> line 64: "There exist many options for describing JSON data". Seems unnecessary. There is no RFC for describing JSON data in JSON format (which is the most logical).

It's good practice to acknowledge others' work, and if nothing else it proves you're not ignorantly reinventing the wheel. CDDL explicitly has validating JSON data in its scope.

> line 65: "JDDF's expressiveness is strategically limited". Sounds apologetic.

Do you mean it sounds too "sorry", or do you mean it sounds too "defensive"? Apologetic has two meanings.

> line 83: "to a given mainstream programming language" -> to "many mainstream programming languages"?

This is a good point. Moved into #17.

> line 86: "Provide a standardized format for errors" - inconsistent with line 48 (see above)

This is non-normative language, and in my view doesn't need to use the precise formal language (i.e. "error indicator"). Is it unclear that I'm laying out the requirement that standard error indicators solve?

> line 89: "JDDF is intentionally designed as a rather minimal schema language". Seems unnecessary. Minimal design is a reasonable expectation of any specification at RFC level.

Perhaps the phrasing could be better, but I'm not sure how. It's reasonable to expect minimalism, but it's also reasonable to go for a comparatively complex validation system like CDDL. Basically, this is me saying that JDDF is shooting for the low-expressiveness, high-simplicity end of the schema spectrum.

> line 95: "C++" - I would propose in addition to C++ (which I assume was chosen as the most basic) map to Haskell types (as one of the most advanced type systems). If I were to implement this spec, I would start from Haskell type for JDDF schema and implement quickcheck (exhaustive combinatorial testing for all possible values in the type space) that can be used against any language implementation (e.g. via HTTP) - it could be reference tester and implementation.

You'll notice that the C++ examples amount to just a few passing references in the subsequent paragraph, and then C++ is never mentioned again. The point is to make some of the terminology more familiar to those who aren't PLT enthusiasts.

Put another way: I don't need more than one example language here, and it's gotta be a language that lots of people, especially those who aren't necessarily to up-to-speed on fancy typesystem terminology, are probably familiar with. C++ fits that bill pretty good, Haskell not so much.

> line 103: "Signed and unsigned 8, 16, and 32-bit integers" - I think 64 bits could be included as SHOULD if not MUST - most (all?) languages support it one way or another, even JavaScript now with BigInt. I think it was included in JSL?

See appendix A.

> line 317: "message". Is the intention to limit JDDF to JSON messages (e.g. rfc7493)? There are other use cases for JSON schemas, e.g. JSON stored in some database - PostgreSQL, Mongo, Elastic.

I'm only talking about messages because it's the only concept the JSON RFC gives me to play with. This doesn't prevent you from using JDDF on data structures that are JSON-like. It just means that I can't formally talk about such things, because there isn't the linguistic infrastructure in place. All I can work with is what I invent, or what the JSON RFC (or some other RFC I can normatively reference) gives me.

> line 402: "finite". It seems unnecessary to specify the list is "finite". Can you express infinite list in JSON?

You could have imagined a version of enum that let you "wildcard" strings. In that case, a finite document could talk about an infinite set of strings.

> line 658: "additionalProperties" - not sure about this idea tbh. JSON Schema became extremely confusing exactly because of that, as it is never clear "additional" to which list of properties. It would be easier of course to figure out for JDDL as static schema analysis is much easier, but still. Also "strict instance semantics" allows to validate with and without allowing additional properties using the same schema in both ways - the original approach seemed better. What's the use case, from data types point of view, to allow additional properties?

The use-case is for situations where, for example, you are working to JDDF-ify some existing data, and you don't want to fail validation just because you forgot about some particular property. Imagine you're retroactively JDDF-ifying your analytics events, for example.

If you'd like to elaborate on this point further, please open a ticket. If you do, please note my aside in https://github.com/jddf/spec/issues/5#issuecomment-586649684.

> line 851: "Though non-root definitions are not syntactically disallowed in correct schemas" - I think they are disallowed, see line 254.

That's a mistake. Good catch. Captured in #18.

> line 1769: int64: RFC7493 says" "An example would be 64-bit integers, even though modern hardware can deal with them, because of the limited scope of JavaScript numbers." It is not longer the case and BigInt can be used in JavaScript code.

It's true that BigInt is a thing now. But BigInt isn't what JSON.parse uses, and so I think the point stands.

**Comment by ucarion** [comment]
After taking a look over my responses, can you close this ticket out @epoberezkin?

**Comment by epoberezkin** [comment]
>> line 65: "JDDF's expressiveness is strategically limited". Sounds apologetic.

> Do you mean it sounds too "sorry", or do you mean it sounds too "defensive"? Apologetic has two meanings.

see #29

**Comment by epoberezkin** [comment]
>>  line 89: "JDDF is intentionally designed as a rather minimal schema language". Seems unnecessary. Minimal design is a reasonable expectation of any specification at RFC level.

> Perhaps the phrasing could be better, but I'm not sure how. It's reasonable to expect minimalism, but it's also reasonable to go for a comparatively complex validation system like CDDL. Basically, this is me saying that JDDF is shooting for the low-expressiveness, high-simplicity end of the schema spectrum.

see #30

**Comment by epoberezkin** [comment]
>> line 402: "finite". It seems unnecessary to specify the list is "finite". Can you express infinite list in JSON?

> You could have imagined a version of enum that let you "wildcard" strings. In that case, a finite document could talk about an infinite set of strings.

see #31

**Comment by epoberezkin** [comment]
>> line 658: "additionalProperties" - not sure about this idea tbh. JSON Schema became extremely confusing exactly because of that, as it is never clear "additional" to which list of properties. It would be easier of course to figure out for JDDL as static schema analysis is much easier, but still. Also "strict instance semantics" allows to validate with and without allowing additional properties using the same schema in both ways - the original approach seemed better. What's the use case, from data types point of view, to allow additional properties?

> The use-case is for situations where, for example, you are working to JDDF-ify some existing data, and you don't want to fail validation just because you forgot about some particular property. Imagine you're retroactively JDDF-ifying your analytics events, for example.

> If you'd like to elaborate on this point further, please open a ticket. If you do, please note my aside in #5 (comment).

see #21

**Comment by epoberezkin** [comment]
>> line 1769: int64: RFC7493 says" "An example would be 64-bit integers, even though modern hardware can deal with them, because of the limited scope of JavaScript numbers." It is not longer the case and BigInt can be used in JavaScript code.

> It's true that BigInt is a thing now. But BigInt isn't what JSON.parse uses, and so I think the point stands.

see #25

**Comment by epoberezkin** [comment]
>> line 86: "Provide a standardized format for errors" - inconsistent with line 48 (see above)

> This is non-normative language, and in my view doesn't need to use the precise formal language (i.e. "error indicator"). Is it unclear that I'm laying out the requirement that standard error indicators solve?

see #32

**Comment by epoberezkin** [comment]
> line 447: The sixth form, properties. Why not struct?

see #33

**Comment by epoberezkin** [comment]
> line 513: "The seventh form, values". why not to call this form "map"? The member would still be "values", but the form name does not have to be the same (and there are other cases where they are not). Also see "type" proposal (#5)

see #34
