### ISSUE TITLE
[PROPOSAL] remove timestamp type

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#22]
>> "timestamp" as a type is very strange... I understand that the idea could be to match SQL or some language types, but depending on the language there may be other types

> It's pretty common in APIs, and is usually well-supported by the serialization/deserialization mechanisms of mainstream languages. It's not terribly hard to support, and users can stick with string if they want to use some other format for dates.

**Comment by epoberezkin** [comment]
"timestamp" validation is not simple without using specialised libraries (which in some cases is unnecessary if all that the code is doing is pushing it to database). There are some weird edge-cases like leap second, optional minutes in time zone offset - it all must be supported. Also I don't think "timestamp" is a type in most languages - it is effectively a specific kind of struct/object.

Also it is semantic string validation (aka "format") that JDDF steers away from (and even JSON Schema 2019-09 made format into annotation), but for some reason makes an exception for timestamp.

It seems to me that JDDF implementations could have extensions for it, and we could even recommend to use "format" for such extensions, or leave it completely to implementations to decide how/if timestamp validation is supported, but the type would be string.

**Comment by ucarion** [comment]
I've implemented RFC3339 validation in 10 different programming languages, and it turns out they all have at least one valid implementation of RFC3339, including the corner cases you mention. Even if they didn't, it's quite tractable to do this validation with a regular expression.

Regarding the string validation slippery-slope argument: the buck genuinely stops here. Timestamps are the only sort of string validation I care to add. I'm gonna oppose #25.

FWIW, Tim Bray suggested the addition of timestamps; timestamps, along with enums, were all he  thought he needed in addition to the initial version of JSL. I've come to really appreciate timestamps as a first-class feature, because it makes the data structures you generate from JTD basically be exactly what you need in most of your code.
