### ISSUE TITLE
[PROPOSAL] support schema bundles

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#23]
>> how to link multiple files? or it's for implementations to decide?

> I've since removed the multi-file stuff in JDDF. Schemas are just one file. If you want to do "linking", you can write a linker / build your own linking stuff on top of JDDF.

**Comment by epoberezkin** [comment]
- cons: simplicity of JDDF
- pros: modularity, maintainability, standardisation. It is difficult to build multiple schema files into one, when each schema has its own definitions - namespace management is required. Not clear how to reference other schema files - it's out of scec and would be confusing.

The proposal is to include schema bundles in JDDF.

Schema bundle is the JSON array of schemas (so no confusion whether JSON document is schema or bundle, it is easy to support by validators).

Optionally, the first schema in the bundle is the main schema (so the bundle can act as a schema).

Each schema in the bundle must be identifies by "id" member that is allowed on the root level only (optional for the main schema in the bundle and for standalone schema).

To reference other schemas in the bundle (and definitions in them) there are two options:
- change "ref". `"ref": "/def"` - reference to local definition. `"ref": "sch/"` - reference to another schema in the bundle. `"ref": "sch/def"` - reference to definition in another schema in the bundle. It means that definition names cannot contain "/". I also allows to reference schema by it's name and self-reference with "ref": "/" (resolves #12).
- add e.g. "extRef" to reference other schemas in  the bundle (and the definitions in them). It is more confusing for self-referencing though.

Having multiple schemas is very common, as otherwise schemas can get really big really fast. JSON Schema-based standards either end up having monstrous schemas (e.g. OpenAPI) or end up with multiple files in a way that is not compatible with validators (e.g. FHIR - they use $ids and $refs incorrectly, because JSON Schema is confusing in this area).

Having schema bundle as an array of schemas, and no changes in schemas are required to combine them into the bundle would make things really simple - I believe it should be standardised in some way, and not left to implementations.

Maybe it could be a separate Internet draft/RFC depending on JDDF?

**Comment by ucarion** [comment]
What are the negative consequences of having this be handled by some tooling that builds on top of JTD? Because if bundles are part of the essential spec, now every single tool which wants to work with JTD has to work with bundles.

**Comment by ucarion** [comment]
Furthermore, aren't we immediately going to be followed up by the next ask: supporting downloading schemas, or importing schemas from files?

**Comment by epoberezkin** [comment]
Bundles are needed in the spec because it also defines the format of the references between the schemas in the bundle. The schema IDs don’t need to be URIs or anything, and how files are connected into the bundle is even less the concern of JDDF than it is of JSON Schema (which says schema $id is not network location where you can download). Supporting bundles is lot more complex than supporting definitions - it just adds one more layer for name spacing and simplified linking of multiple files into one - they become just elements of the array.

**Comment by ucarion** [comment]
Having to carry around an array of schemas, instead of just one schema, is a nontrivial added requirement. When validating, validators would need to specify which schema is the "entrypoint" into validation, for example. If schemas specify their own names, validators will have to make sure there aren't two schemas with the same name. Users of schemas would need to make sure they don't accidentally bundle the wrong version of a schema they depend on, which happens to have the same name.

All of this for a feature that some "linker" tooling could implement themselves ... OpenAPI, for example, demonstrates how even JSON Schema's vast reference system wasn't good enough, and they implemented their own namespacing system anyway.

**Comment by epoberezkin** [comment]
> When validating, validators would need to specify which schema is the "entrypoint" into validation, for example.

As I wrote, the first one can be considered entry point.

> If schemas specify their own names, validators will have to make sure there aren't two schemas with the same name.

Correct, but it's trivial

> Users of schemas would need to make sure they don't accidentally bundle the wrong version of a schema they depend on, which happens to have the same name.

That will be caught

> All of this for a feature that some "linker" tooling could implement themselves

It is impossible to maintain all schema in a single file, so any project with JSON schema would need to have some way to link multiple schemas in one. And linking without spec support is much more complex. It requires:
- a separate keyword to reference schemas and definitions in other files
- merging all schemas and all definitions into a single root definitions object - that requires renaming definitions that conflict and also changing all the refs that point to them, as there can be duplicate definition names in different schemas (same problem that you identify for linking, but it's more difficult to solve than what is proposed).
- even if this is all done, it won't be cross platform, so the schema collection cannot be used - only a linked file.

This is much easier to support on validator level than to have a separate linking process, but it just means this support won't be cross platform because it's not part of the spec.

**Comment by epoberezkin** [comment]
Consider this artificial example of schemas that should be linked.

```json
{
  "definitions": {
    "foo": {"type": "string"}
  }
  "properties": {
    "foo": {"ref": "foo"}
  }
}
```

**Comment by epoberezkin** [comment]
Consider this artificial example of 2 schemas that should be linked.

## Option 1.

No spec support, custom "id" and "extRef" keywords are used to link to external schemas.

Main schema

```json
{
  "definitions": {
    "foo": {"type": "string"}
  },
  "properties": {
    "foo": {"ref": "foo"},
    "bar": {"extRef": "bar"},
    "baz": {"extRef": "bar/foo"}
  }
}
```

Linked schema

```json
{
  "id": "bar",
  "definitions": {
    "foo": {"type": "number"}
  },
  "properties": {
    "zoo": {"ref": "foo"},
  }
}
```

To link these two schemas with minimal changes (without inlining references, which is not possible in general case because of recursion), you would need this schema, that has all its references changed :

```json
{
  "definitions": {
    "foo-1": {"type": "string"},
    "foo-2": {"type": "number"},
    "bar": {
      "properties": {
        "zoo": {"ref": "foo-2"},
      }
    }
  },
  "properties": {
    "foo": {"ref": "foo-1"},
    "bar": {"ref": "bar"},
    "baz": {"ref": "foo-2"}
  }
}
```

So you would have to deep-walk all the schemas and update all the references for it.


## Option 2 (proposed).

Bundle support in spec, standard "id" and either "ref" or "extRef keywords are used to link to external schemas (as described above in the issue). The example is with "extRef".

The same two schemas have to be linked, but in this case all that has to be done is to merge them in array and check that there are no duplicate IDs. Given that IDs would logically match filenames (even though it's not required by the spec, that's what people usually do anyway), they are likely to be different, but it's something that is easy to check - only top level needs to be accessed, no schema traversal.

```json
[
  {
    "definitions": {
      "foo": {"type": "string"}
    },
    "properties": {
      "foo": {"ref": "foo"},
      "bar": {"extRef": "bar"},
      "baz": {"extRef": "bar/foo"}
    },
  },
  {
    "id": "bar",
    "definitions": {
      "foo": {"type": "number"}
    },
    "properties": {
      "zoo": {"ref": "foo"},
    }
  }
]
```

This proposal is much simpler to implement in validators, without separate complex linking logic.

**Comment by ucarion** [comment]
I see two facts that together make me think this proposal is a gateway to massively complicating the specification.

1. On this proposal, the main useful artifact for almost any tooling that wants to deal with JDDF schemas isn't in fact a schema, but a bundle of schemas. All tooling will need to be aware of bundles, because schemas on their own are not sufficient.

2. Folks are going to immediately want to have some sort of relation to the filesystem, so that they can reference a schema in an adjacent file via some sort of `extRef` mechanism. I can assure you that I will not allow JDDF to be tied to the filesystem, HTTP, or any other mechanism for referencing "remote" resources. I will not add normative references to URIs or any related specifications to the spec at this time.

Given that I'm not willing to tie JDDF to filesystems/HTTP/whatever (I would prefer that people choose to tie filesystems/HTTP/whatever into JDDF however they see fit, and not have JDDF prescribe such a relation), that means that all implementations are going to feel pressure to add extensions that "auto-generate" bundles from the filesystem/HTTP/whatever, for example by assuming that all of the json files in a directory are meant to constitute a bundle, and any URL they reference in `extRef` is meant to be downloaded and added to the bundle.

But implementing integrations into filesystems/HTTP/whatever is _very_ complicated to do properly. Suffice it to say that paths/URLs/etc are massive, complex beasts that most implementations will implement different subsets of, and many of these things don't have consistent standardized specifications.

In practice, this will mean the very balkanization you seem to already be worried about, as different implementations across the many levels of JDDF tooling -- validators, code generators, documentation explorers, etc -- all implement different subsets of the "bundling" stuff. OpenAPI already lives in this world.

Instead, I think we should accept that there will likely be tools out there which compile "JTD plus URI / filesystem references" into a single actual JTD schema JSON object. You see this phenomenon all the time in the OpenAPI world, where the only way to have an OpenAPI schema actually be usable by most tooling is to first bake all of your multi-file stuff into a single file.

**Comment by epoberezkin** [comment]
> On this proposal, the main useful artifact for almost any tooling that wants to deal with JDDF schemas isn't in fact a schema, but a bundle of schemas. All tooling will need to be aware of bundles, because schemas on their own are not sufficient.

I am not sure I follow the logic. Schema is sufficient on its own if it has no external references - that’s the current spec, and I am not proposing to drop it. Bundle, collection or any other grouping of schemas simply define a namespace to look up external references in - array representation as part of the spec is just one of the option (it could be an object with keys - possibly easier to look up and no need for id then) - what is important that it is a namespace where the schemas can be found by their name.

> Folks are going to immediately want to have some sort of relation to the filesystem, so that they can reference a schema in an adjacent file via some sort of extRef mechanism.

People wanted it in JSON Schema because it used URIs - that was a design mistake to say that schema ID is URI, but it is not a network location where the schema can be retrieved. It was the source of massive confusion. I am proposing plain names, without any restrictions other that the name is uniques per namespace and that this namespace is not hierarchical.

> I can assure you that I will not allow JDDF to be tied to the filesystem, HTTP, or any other mechanism for referencing "remote" resources. I will not add normative references to URIs or any related specifications to the spec at this time.

I am also against it. Schemas can be stored in any system and it’s for the application to define how namespace is managed.

The only reason I am proposing a specific bundle format in addition to namespace is because many people want to ship the linked of schemas as a single schema file. Linking multiple schemas into a single schema is complex, because you have to manage namespace conflicts in definitions (see example). Linking multiple schemas into the bundle is trivial.

Going back to the problems this proposal solves, they are:

1. Managing multiple [mutually] dependent schemas is very difficult in a single file - almost everybody splits them. So some way to reference other schemas is needed in one-level namespace is the simplest solution here - no need to tie to any IO / storage.
2. Linking multiple schemas into something that can be used to be validated against. Again - specified bundle format is the simplest solution here, effectively making bundle a schema with the first schema object being the main one.

We had a similar argument in JSON Schema - and they chose to have multi-level definitions, base URI, etc - all very complex. Without bundle, folks would 100% want multi-level definitions, nobody would be thrilled to link schemas the way I described above - it’s very error prone. And multi-level definitions is definitely more complex than single level namespace and bundle.

**Comment by ucarion** [comment]
I'm not denying that linkers are potentially useful. But I don't see why we need to bring linkers into the spec -- why does cross-file linking need to be portable?

In other words, can the portable thing be the JTD schema -- something simple enough that both huamns and machines can read/write -- and there are non-portable technologies built on top of it, that do stuff like letting you reference other files in a schema, and handle joining up those references, and deduping/namespacing/name-mangling?
