### ISSUE TITLE
[PROPOSAL] string-encoded 64-bit integers

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#25]
While JSON supports unlimited integer size, they are not cross-platform, and we limit JSON integers it to 32 bits here - I agree with that.

At the same time, it is a common practice (and it is recommended by some RFCs) to encode 64-bit numbers as strings.

The proposal is to add 2 string-encoded 64-bit integer types "int64str", "uint64str" - many APIs use such strings as parameters for large table IDs.

Different languages may choose to leave them as strings (e.g. JS) or to convert to 64-bit integers.

As a side comment, it seems less stretching into formats territory than "timestamp" (see #22) as 64-bit integers are widely supported as specific types in most languages and not with structs, as timestamps. Also validation / conversion of 64-bit integers from strings is straightforward.

**Comment by ucarion** [comment]
This was formerly in the spec, and removed per the suggestion of the json@ietf.org mailing list. Please see discussion there:

https://mailarchive.ietf.org/arch/msg/json/W5k7W204RrpErkQswys-FNeTKH4
https://mailarchive.ietf.org/arch/msg/json/sBVjFD5Czobj5QAR6XaGAVcUdlU

**Comment by epoberezkin** [comment]
Sorry, I don’t think it was in the spec unless I missed, I think “int64” was in the spec, but the proposal is different.

The suggestion is to have schema:

```json
{"type": "int64str"}
```

to describe the data like

```json
"123456789"
```

not

```json
123456789
```

I.e. not a large number but a string defining 64 bit number.

**Comment by ucarion** [comment]
This alternative is asked and answered in the mailing lists. Please see the discussion there -- the problem is that there are multiple, mutually compatible ways of encoding numbers as strings. It's quite inefficient to store high-precision numbers as just stringified decimal numbers.

Also, on your proposal, the spec would have to also limit the numerical value of the encoded number, no? So that means the spec would have to specify how to decode the number?

Also note in the introduction of the spec:

```
   The principle of common patterns in JSON is why JDDF does not support
   64-bit integers, as these are usually transmitted over JSON in a non-
   interoperable (i.e., ignoring the recommendations in Section 2.2 of
   [RFC7493]) or mutually inconsistent (e.g., using hexadecimal versus
   base64) ways.  Appendix A.1 further elaborates on why JDDF does not
   support 64-bit integers.
```

Note the parenthetical:

> e.g. using hexadecimal versus base64
