### ISSUE TITLE
Clarify how ambiguous forms should be interpreted

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#26]
What should be the schema meaning when schema has members from two different forms?

Example:

```json
{
  "properties": {},
  "type": "string"
}
```

Currently it is ambiguous. Possible interpretations:

- schema syntax SHOULD be invalid
- schema is considered a union of two forms
- schema meaning is undefined - to be decided by implementations to allow extensions
- one of the forms is matched first and the extra member is considered optional

What should be the schema meaning when schema has members from two different forms, but one of the members is invalid?

Example (that Ajv would have to  support): 

```json
{
  "properties": {},
  "type": "object"
}
```

- schema syntax SHOULD be invalid (it would mean that Ajv would have to support not only extension of JDDF, but also invalid JDDF schemas)
- schema is considered a union of two forms
- schema meaning is undefined - to be decided by implementations to allow extensions (seems better from Ajv support point of view)
- one of the forms is matched first and the extra member is considered optional

**Comment by ucarion** [comment]
The question this ticket asks is answered in the spec, and it's a core property of the syntax of JDDF that valid schemas cannot take on multiple forms at once.

> Currently it is ambiguous

It is not. If you follow the CDDL syntax definition of schemas, you'll see that your example schema is actually not a schema at all. It doesn't follow the syntax rules. Validation is defined only for correct JDDF schemas, and that's not a correct JDDF schema.

All of the implementations of JDDF handle this problem, raising errors to the effect of "invalid form".

The question of how AJV should handle the example you give is better handled within the context of AJV specifically, because of its special considerations. I'm inclined to think this is not a JDDF spec concern.

Please re-open this ticket if you think I've misunderstood what your point here is.
