### ISSUE TITLE
[PROPOSAL] union type

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#27]
Both for primitive and compound values:

```
{
  "union": [
    <schema1>,
    <schema2>,
    <schema3>
  ]
}
```

**Comment by ucarion** [comment]
What mainstream static type systems support "bare" unions like these? I can think of TypeScript and C, but not much else...

I'm concerned that there isn't going to be useful code generation you can do from schemas that use `union`.

**Comment by epoberezkin** [comment]
Go supports them via interface, Haskell supports them.

**Comment by epoberezkin** [comment]
> I'm concerned that there isn't going to be useful code generation you can do from schemas that use union.

Type generation - language dependent. Validation and parsing - it is possible in all languages.

**Comment by ucarion** [comment]
Go and Haskell both support _tagged_ unions. The tag is simply anonymous, and implemented through vtable-esque stuff which the runtime can check.

This distinction matters: how are you supposed to know which variant of a union you're supposed to generate from JSON, if there's no "tag" on the JSON to tell you?

Put another way: if I give you this Haskell:

```hs
data Foo = A String | B String
```

How would you know what variant of `Foo` generate from `"asdf"`? This matters, because having useful data structures to generate from JDDF which work with (in Haskell's case, Aeson) is a core use-case.

> Type generation - language dependent. Validation and parsing - it is possible in all languages.

Type generation can be language dependent, but it must be broadly-supported for a feature to be accepted into JDDF. JDDF is strategically limited to be portable yet useful.

**Comment by epoberezkin** [comment]
> Go and Haskell both support tagged unions. The tag is simply anonymous, and implemented through vtable-esque stuff which the runtime can check.

Anonymous tags are not included into JSON usually.

> How would you know what variant of Foo generate from "asdf"? This matters, because having useful data structures to generate from JDDF which work with (in Haskell's case, Aeson) is a core use-case.

E.g. the first one that matches the union. That's the spec's decision what happens in this case, there are several options here.

> JDDF is strategically limited to be portable yet useful.

Union seems common enough to leave it out.

**Comment by ucarion** [comment]
> Anonymous tags are not included into JSON usually.

I'm not sure I know how you're coming to this conclusion. At least in the Aeson world, the convention is to rely on `TaggedObject`, rather than `UntaggedObject`, in `SumEncoding` https://hackage.haskell.org/package/aeson-1.4.6.0/docs/Data-Aeson-TH.html#g:1 because of the exact example I gave before. See the note from the Aeson docs on `UntaggedObject`:

> Constructor names won't be encoded. Instead only the contents of the constructor will be encoded as if the type had a single constructor. JSON encodings have to be disjoint for decoding to work properly.

That's why Aeson's default configuration uses `TaggedObject` -- see `defaultOptions` in the linked docs.

Arbitrary untagged unions can't be safely round-tripped through JSON. For example, you can't reliably convert `B "foo"` into JSON and then back into `B "foo"` when `B` is from:

```hs
data Foo = A String | B String
```

So our options are:

1. Live with not having round-trippable things. This is not great, and `union` would be the sole data structure that, even if you know the JTD schema of the JSON you're looking at, you still can't convert it back into the data structure it was serialized from. This is going to be a problem in a large swathe of business software.
2. Make the rules of `union` work out so that they are always round-trippable -- in other words, so that the the variants of a `union` are always mutually exclusive. Doing so is a pretty big and subtle endeavor to properly specify. I'm not willing to do the work to write such a specification.

For this reason, I think we should not include untagged unions. We shouldn't sacrifice round-tripping, and the work to make round-trippable untagged unions is too great.

Would you object greatly if I were to reject this proposal?
