### ISSUE TITLE
[PROPOSAL] meta-schema

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#28]
It can be achieved either with more generic union (#27) or with schema bundle (#23) - the meta-schema can be defined as the collection of schemas, one per form.

We could even specify separate meta-schemas for each form - and then the process of validating the schema will be defined as validating against several meta-schemas, so it can be resolved independently of #27 and #23

**Comment by ucarion** [comment]
What would be gained from this proposal? It would need to be weighed against the downside of adding "just one more feature".

**Comment by epoberezkin** [comment]
> What would be gained from this proposal? It would need to be weighed against the downside of adding "just one more feature".

That validation of the schema itself is possible with the same validator.

**Comment by ucarion** [comment]
How do meta-schemas fit into the specification? What would need to be added to the English?

**Comment by epoberezkin** [comment]
The meta-schema itself with the language description that any schema that is syntactically valid according to the spec, MUST also be valid as JSON document against the meta-schema (in the sense of valid JSON document in the spec).

**Comment by ucarion** [comment]
Ok, how about this as next steps for this ticket.

If JDDF/JTD comes to have nearly-sufficient capability to describe its own shape -- in particular, if it has the ability to describe the "forms" concept in some way, then I will add an addendum to the spec that describes a meta-schema. However, I will still need to keep the CDDL syntax around.

If we agree on this, then I think we can close this ticket out, and remember to create a new ticket if other features are accepted.

**Comment by epoberezkin** [comment]
> However, I will still need to keep the CDDL syntax around.

I never objected to that

> addendum to the spec that describes a meta-schema

Not sure what is the trade-off between being addendum or part of the spec?

> If JDDF/JTD comes to have nearly-sufficient capability to describe its own shape

The point of the ticket is that I believe that JDDF/JTD should have the ability to describe its syntax, either by extending the spec to cover the schemas or by changing the schemas to fit into the spec (e.g. via using tagged union for schema documents - although it leads to the redundancy, so it is not my preferred option).

To me it is to some extent a contradiction when on one hand we say that tagged union is expressive enough for data type / validation scenarios, and on another hand we say that we do not want to use it as it is not sufficiently expressive and leads to verbosity.

**Comment by ucarion** [comment]
If your request is that JDDF/JTD should be made more powerful, let's focus the conversation on those specific things you'd like to have added. Please feel free to call out if a particular feature is related to meta-schemas.

I don't think it's a problematic contradiction. JDDF will certainly not be powerful enough to describe, for example the fact that you can't have the same property mentioned in `properties` and `optionalProperties`. Schemas happen to be structures far more complex than what most applications ever need.

If making good meta-schemas possible requires making _all_ schemas redundant, or adding features to the spec which we otherwise wouldn't need, then I think we should not worry about meta-schemas.
