### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#3]
"JSON schema" is generic term that means, literally, "schema for JSON".

It cannot be used as a brand or trademark once there is an another schema for JSON.

@handrews could you please comment why you insisted on @ucarion renaming JSL to JDDF?

**Comment by epoberezkin** [comment]
The alternative could be "JSON Type Schema"

**Comment by ucarion** [comment]
JSL was provoking confusion with JSON Schema. I agree that it's a bizarre situation we're in -- JSON Schema's name is akin to naming your dog, "dog". But note that it's a situation that the current JSON Schema maintainers inherited.

I am not shying away from calling, even for the purposes of SEO and whatnot, JDDF a "Schema Format for JSON", because that's plainly what this project is. But I have no appetite for causing a furor over the name of the project. That ship has sailed, and to re-open this can of worms would be to start a fight.

Can we agree to consider this matter settled?

**Comment by epoberezkin** [comment]
My understanding of this spec purpose, please correct me if I am wrong:

- express data type (not just data format) in JSON
- generate type definitions for multiple (all?) programming languages
- validate data type and/or generate type validators code
- generate code for correct and efficient JSON parsing/serialisation into/out of expected application types

JDDF does not reflect it as it has no "type" in it.

I agree with the argument of avoiding confusion: even though "JSON schema" is a generic, "JSON Schema" (with capital S) is a brand (even if not protectable, it is recognised), so having both JSON and schema in another name can indeed lead to confusion.

Given that all listed spec objectives have “type” in it, and that good mapping to types is the USP of this spec, I propose to rename it to JSON Type Definition (JTD) - it is a shorter, more memorable name, that better reflects this spec purpose and objectives.

**Comment by philsturgeon** [comment]
> Can we agree to consider this matter settled?

**Comment by ucarion** [comment]
Hmm, JTD is quite a sensible name. It can also go by the name of "JSON Typedef" in more common parlance. I was skeptical that we'd find a name sufficiently better than JDDF that it'd be worth pursuing, but this might be it.

I will point out that "data definition" is a more proper definition of what JDDF does than "type definition". But I also recognize that JTD has connections to DTD.

There are nice parallels too: JSON Schema and XML Schema are similar -- both are hulking specs that aren't especially amenable to building simple tooling atop of (but great for building tooling companies on top of, because they're popular, extensible, and full of footguns), whereas DTD and "JTD" are comparably smaller and more KISS in spirit.

Let's keep this ticket open. I'm going to continue mulling over this name, and bounce it off of folks IRL. I'll also look into how difficult it would be to change this at the IETF level as well. Thank you for this suggestion!
