### ISSUE TITLE
Mandate that custom keywords have some prefix

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#39]
E.g. “x-“ or even any “vendor” prefix

**Comment by ucarion** [comment]
I'm not sure I see why this is better than nesting properties inside a `metadata` field. Doing `x-` stuff is deprecated within the context of HTTP headers: https://tools.ietf.org/html/rfc6648

**Comment by ucarion** [comment]
I am closing this ticket, and all other open tickets on this repo, in favor of https://github.com/jsontypedef/json-typedef-spec. I will now summarize the delta between the state of the spec as you last commented on it:

- I incorporated #3. The project is now called JSON Type Definition.
- I did not incorporate #5. It complicated the spec, and meant that there was more than one way of doing the same thing.
- I did not incorporate #8. The need for numeric enums is far lesser than the need for string enums.
- I did not incorporate #10. It is not usually wise to force users to say the same thing twice in a schema, and the rules for what makes a valid schema are complicated as it is.
- I did not end up incorporating #15. I believe it's sufficiently obvious that a serializer/deserializer is a form of code generation.
- I did not incorporate #16, because custom keywords are no longer a thing. See last bullet point.
- I incorporated #17.
- I incorporated #18.
- I incorporated #20, after we got onto the same page there.
- I did not incorporate #21. additionalProperties is, in my view, the best name.
- I did not incorporate #22. Timestamps are important enough to be a first-class citizen.
- I did not incorporate #23. It is insufficiently well-defined, and I think the problems in that ticket can be addressed by tooling on top of JTD.
- I did not incorporate #27. Untagged unions are very complex to restrict to still be round-trippable, and not broadly supportable by code generators.
- I incorporated #29.
- I incorporated #30.
- I incorporated #32.
- I didn't have to fix #36 thanks to your suggestion in #20.
- I incorporated #37.
- I went with #38, rather than #39, as an approach for handling custom keywords. `x-`-based stuff is a hassle to deal with in most languages, where you'd otherwise like to parse JTD schemas into structs -- it's hard to deal with "arbitrary" keywords.

I really appreciate all the hard work that went into these discussions. Let's continue any further conversation in https://github.com/jsontypedef/json-typedef-spec.
