### ISSUE TITLE
[PROPOSAL] allow types array/object/struct/map

### ISSUE THREAD

**Issue by epoberezkin** [jddf/spec#5]
>> require (allow?) type array/object (but must be compatible with the form). If you require, you would be able to define loose meta-schema for all forms.

> I don't understand this suggestion. Can you elaborate?

**Comment by epoberezkin** [comment]
The proposal is to make "type" not a separate form, but instead make it required member in "primitive value" and "enum" forms (see proposal #8) and an optional member in other forms.

Proposed type names:

- primitive types, as defined - to be used in "primitive value" form and in "enum" form (that can be merged into one form with required "type" and optional "enum" member)
- "object", that implementations SHOULD support to mean either "struct" or "map" and that is allowed to be used in `properties`/`struct`, `discriminator` and `map` forms
- "struct", that implementations MUST support and that is allowed to be used in `properties` and `discriminator` forms (see the proposal to merge them into `struct` form)
- "map", that implementations MUST support and that is allowed to be used in `values`/`map` form
- "array", that implementations MUST support and that is allowed to be used in `elements`/`array` form

**Comment by ucarion** [comment]
What is the benefit of this proposal?

**Comment by epoberezkin** [comment]
to simplify migration and "explicit over implicit".

How would spec behave in this case:

```json
{
  "type": "object",
  "properties": {
    "foo": {},
    "bar": {}
  },
  "required": ["foo", "bar"]
}
```
?

My understanding that required will be ignored as custom keyword (and some future Ajv linter can check that all properties are in required or ask to move to optional. But then there are two possibilities:

1. It recognises it as "properties" form with some ignored custom keyword
2. It recognises it as "type" form with incorrect type

Making "type" not a form but a member of all other forms (optional in some cases) actually simplifies the spec and also simplifies the migration.

Also, this will be interpreted very differently in JDDF and in JSON Schema:

```json
{
  "type": "number",
  "properties": {
    "foo": {},
    "bar": {}
  },
  "required": ["foo", "bar"]
}
```

If we make it invalid in JDDF "properties" form it's easy to fix, but if "properties" form simply ignores "type" it creates ambiguity.

**Comment by ucarion** [comment]
The `properties` keyword and the `type` keyword are mutually exclusive. All of the validators will error out on that "schema", saying it has an invalid form. Is that satisfactory? It brings the problem front-and-center, and doesn't quietly do the wrong thing.

**Comment by epoberezkin** [comment]
The spec allows to have unrecognised members, so if the form is matched as "properties" why would it not allow wrong "type". "Type" as a form does not make sense to me, as "type" is a cross-cutting concern - every JSON data has type. What you call "type" form describes primitive value, but it looks like it is the only category of values that has a type.

**Comment by ucarion** [comment]
I think there's an interesting change we could make to JDDF/JTD that could address a lot of issues at once, and it requires only rather minimal "purity"/"cleanness" compromises.

I'm proposing that `type` be required on all schemas. Its value must be one of:

* `any` -- indicates what is today called the "empty" form.
* The values it can already take on (`boolean` ... `uint32`) -- indicates what is today called the "type" form.
* `enum` -- indicates the enum form.
* `array` -- indicates what is today called the "elements" form.
* `object` -- indicates what is today called the "properties" form.
* `map` -- indicates what is today called the "values" form.
* `taggedUnion` -- indicates what is today called the "discriminator" form.

We would not make any changes to how any of the forms work, although we could refactor the spec to call the forms by their corresponding `type` value. Doing so would give us these benefits:

1. An increase in compatibility with JSON Schema. Assuming most JSON Schema schemas which have `type: "object"` are mostly using `properties`, then more schemas can be grandfathered into JTD. I think this would fix the _spirit_ of this GitHub issue, although the solution is a bit different.
2. It makes writing a meta-schema mostly possible, because now schemas are a tagged union, and `type` is the tag. Some constraints (such as the value of `enum` can't contain duplicate strings, and you can't re-specify a `discriminator`'s `tag` in one of its `mapping` values) can't be expressed, but most of the structure of JTD is now possible to capture in a JTD schema.

In an ideal world, I would have made `type: "object"` be `type: "struct"` instead, because maps are JSON objects too. But I think I can live with that compromise if it helps with migration.

Do you think this would be a valid way to move forward? Any JSON Schema schema which uses only `type: "object"` and `properties` would also be a valid JTD schema, with the caveat that `properties` means "required" in JTD, but by default means "optional" in JSON Schema.

**Comment by epoberezkin** [comment]
It would solve the migration problem, at the price of making schemas heavier.

Aesthetically “properties” and “elements” without type look better, that’s why I proposed type as optional.

I also initially thought that having type as tag would allow meta-schema as tagged union, but then I realised that union without tag is a common case too and probably needed anyway.

I think this issue is difficult to decouple from #7 (union without tag) and #10 (common properties in tagged union, merging discriminator and properties in one form).

**Comment by epoberezkin** [comment]
For example, in JSON schema I have to write (doing it right now):

```json
{
  "type": "object",
  "additionalProperties": false,
  "required": ["recipient"],
  "properties": {
    "recipient": {
      "type": "string"
    }
  }
}
```

and it is very bulky.

I really liked the early JDDF when it was just:

```json
{
  "properties": {
    "recipient": {
      "type": "string"
    }
  }
}
```

and it meant the same (assuming strict instance, which is the most common case)

Now there is "additionalProperties" (which I am not a fan of - the issue is coming) and the proposal is to add required "type". We are just one step from being where we started.

**Comment by ucarion** [comment]
> We are just one step from being where we started.

I take this point well, and is my concern with the proposal too. 

Just to put it on the record, my take on this is that there is a trilemma at the center of this issue:

1. It would be nice if JDDF schemas were terse.
2. It would be nice if JDDF schemas were limited to few different "shapes", so that code generation, schema inference, generating docs from schemas, etc. is simpler.
3. It would be nice if JDDF could describe itself.

I don't think all three can be done. I have unabashedly sacrificed (3).

---

As an aside:

> and it meant the same (assuming strict instance, which is the most common case)

Strict instance semantics aren't a thing anymore. The words don't appear in the spec. Everything is in "don't allow extra properties" mode by default, and "additionalProperties: true" changes that _for just the schema in question_. "additionalProperties" doesn't affect sub-schemas.

**Comment by ucarion** [comment]
If you believe this ticket is tied to #10, then I think we should continue the discussion we're having there. I've given my thoughts on #7 in that ticket.

**Comment by epoberezkin** [comment]
I will comment in #7 and #10 separately.

Ajv could allow optional types as long as the type matches, no need to have type in JDDF schema. 

The question to address in spec semantics is how the schema would be interpreted if both "type" and "properties" is present (and any other combinations) - at the moment, as JDDF allows custom members without whitelisting them, it leads to ambiguity - see #26
